export type User = {
  id: string,
  username: string,
  email: string,
  phone: string,
  role: RoleEnum,
  updatedAt: Date,
  createdAt: Date,
  status: StatusEnum,
  hasEp: boolean,
};

export enum StatusEnum {
  Active = 'Активен',
  Blocked = 'Заблокирован',
}

export enum RoleEnum {
  User = 'Пользователь',
  Admin = 'Администратор',
}

export const users: User[] = [
  {
    id: crypto.randomUUID(),
    username: 'ivanov 1',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.User,
    updatedAt: new Date(2018,1, 11),
    createdAt: new Date(2017, 3, 5),
    status: StatusEnum.Active,
    hasEp: true,
  },
  {
    id: crypto.randomUUID(),
    username: 'aaosipovich 2',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 828-88-18',
    role: RoleEnum.User,
    updatedAt: new Date(2020,1, 5),
    createdAt: new Date(2015, 3, 1),
    status: StatusEnum.Blocked,
    hasEp: true,
  },
  {
    id: crypto.randomUUID(),
    username: 'cxzzxc 3',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.User,
    updatedAt: new Date(2022,6, 8),
    createdAt: new Date(2021, 5, 23),
    status: StatusEnum.Active,
    hasEp: true,
  },
  {
    id: crypto.randomUUID(),
    username: 'gfhfgh 4',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.User,
    updatedAt: new Date(2015,1, 11),
    createdAt: new Date(2013, 3, 5),
    status: StatusEnum.Active,
    hasEp: false,
  },
  {
    id: crypto.randomUUID(),
    username: 'iouikuj 5',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.User,
    updatedAt: new Date(2018,1, 11),
    createdAt: new Date(2017, 3, 5),
    status: StatusEnum.Active,
    hasEp: false,
  },
  {
    id: crypto.randomUUID(),
    username: 'ivanov 6',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.Admin,
    updatedAt: new Date(2018,1, 11),
    createdAt: new Date(2017, 3, 5),
    status: StatusEnum.Active,
    hasEp: true,
  },
  {
    id: crypto.randomUUID(),
    username: 'iouikuj 7',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.User,
    updatedAt: new Date(2018,1, 11),
    createdAt: new Date(2017, 3, 5),
    status: StatusEnum.Active,
    hasEp: false,
  },
  {
    id: crypto.randomUUID(),
    username: 'ivanov 8',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.User,
    updatedAt: new Date(2018,1, 11),
    createdAt: new Date(2017, 3, 5),
    status: StatusEnum.Active,
    hasEp: true,
  },
  {
    id: crypto.randomUUID(),
    username: 'iouikuj 9',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.User,
    updatedAt: new Date(2018,1, 11),
    createdAt: new Date(2017, 3, 5),
    status: StatusEnum.Active,
    hasEp: false,
  },
  {
    id: crypto.randomUUID(),
    username: 'ivanov 10',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.Admin,
    updatedAt: new Date(2018,1, 11),
    createdAt: new Date(2017, 3, 5),
    status: StatusEnum.Active,
    hasEp: true,
  },
  {
    id: crypto.randomUUID(),
    username: 'iouikuj 11',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.User,
    updatedAt: new Date(2018,1, 11),
    createdAt: new Date(2017, 3, 5),
    status: StatusEnum.Active,
    hasEp: false,
  },
  {
    id: crypto.randomUUID(),
    username: 'ivanov 12',
    email: 'asidorov@vtb.ru',
    phone: '+7 (916) 888-88-88',
    role: RoleEnum.Admin,
    updatedAt: new Date(2018,1, 11),
    createdAt: new Date(2017, 3, 5),
    status: StatusEnum.Active,
    hasEp: true,
  },
];


